# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.search_extensions_schema import SearchExtensionsSchema

class TestSearchExtensionsSchema(unittest.TestCase):
    """SearchExtensionsSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchExtensionsSchema:
        """Test SearchExtensionsSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchExtensionsSchema`
        """
        model = SearchExtensionsSchema()
        if include_optional:
            return SearchExtensionsSchema(
                appeals = True,
                centre_point = True,
                heading = True,
                unlimited_radius = True,
                project_type = True,
                num_new_houses = True,
                document_metadata = True,
                proposed_unit_mix = True,
                proposed_floor_area = True,
                num_comments_received = True
            )
        else:
            return SearchExtensionsSchema(
        )
        """

    def testSearchExtensionsSchema(self):
        """Test SearchExtensionsSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
