# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.stats_response_schema import StatsResponseSchema

class TestStatsResponseSchema(unittest.TestCase):
    """StatsResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsResponseSchema:
        """Test StatsResponseSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsResponseSchema`
        """
        model = StatsResponseSchema()
        if include_optional:
            return StatsResponseSchema(
                council_development_activity_level = 'low',
                approval_rate = 1.337,
                refusal_rate = 1.337,
                average_decision_time = ibex_client.models.average_decision_time_by_project_type.Average Decision Time by Project Type(
                    small_residential = 1.337, 
                    tree = 1.337, 
                    large_residential = 1.337, 
                    home_improvement = 1.337, 
                    mixed = 1.337, 
                    medium_residential = 1.337, ),
                number_of_applications = ibex_client.models.number_of_applications_by_type.Number of Applications by Type(
                    non_material_amendment = 56, 
                    discharge_of_conditions = 56, 
                    listed_building_consent = 56, 
                    advertisement_consent = 56, 
                    householder_planning_application = 56, 
                    tree_preservation_order = 56, 
                    lawful_development = 56, 
                    change_of_use = 56, 
                    full_planning_application = 56, 
                    conservation_area = 56, 
                    utilities = 56, 
                    unknown = 56, 
                    environmental_impact = 56, 
                    section_106 = 56, 
                    pre_application = 56, 
                    other = 56, ),
                number_of_new_homes_approved = 56
            )
        else:
            return StatsResponseSchema(
                council_development_activity_level = 'low',
                approval_rate = 1.337,
                refusal_rate = 1.337,
                average_decision_time = ibex_client.models.average_decision_time_by_project_type.Average Decision Time by Project Type(
                    small_residential = 1.337, 
                    tree = 1.337, 
                    large_residential = 1.337, 
                    home_improvement = 1.337, 
                    mixed = 1.337, 
                    medium_residential = 1.337, ),
                number_of_applications = ibex_client.models.number_of_applications_by_type.Number of Applications by Type(
                    non_material_amendment = 56, 
                    discharge_of_conditions = 56, 
                    listed_building_consent = 56, 
                    advertisement_consent = 56, 
                    householder_planning_application = 56, 
                    tree_preservation_order = 56, 
                    lawful_development = 56, 
                    change_of_use = 56, 
                    full_planning_application = 56, 
                    conservation_area = 56, 
                    utilities = 56, 
                    unknown = 56, 
                    environmental_impact = 56, 
                    section_106 = 56, 
                    pre_application = 56, 
                    other = 56, ),
                number_of_new_homes_approved = 56,
        )
        """

    def testStatsResponseSchema(self):
        """Test StatsResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
