# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.search_response_schema import SearchResponseSchema

class TestSearchResponseSchema(unittest.TestCase):
    """SearchResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchResponseSchema:
        """Test SearchResponseSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchResponseSchema`
        """
        model = SearchResponseSchema()
        if include_optional:
            return SearchResponseSchema(
                council_id = 56,
                council_name = '',
                planning_reference = '',
                url = '',
                proposal = '',
                raw_address = '',
                raw_application_type = '',
                normalised_application_type = 'non-material amendment',
                application_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                decided_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                raw_decision = '',
                normalised_decision = 'Approved',
                geometry = '',
                appeals = [
                    ibex_client.models.planning_appeal_information.Planning Appeal Information(
                        appeal_ref = '', 
                        appeal_url = '', 
                        start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        decision_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        decision = '', 
                        case_type = '', )
                    ],
                project_type = 'small residential',
                centre_point = '',
                heading = '',
                num_new_houses = 56,
                document_metadata = [
                    ibex_client.models.document_metadata_item_schema.DocumentMetadataItemSchema(
                        date_published = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        document_type = '', 
                        description = '', 
                        document_link = '', )
                    ],
                proposed_unit_mix = ibex_client.models.proposed_unit_mix_schema.ProposedUnitMixSchema(
                    total_existing_residential_units = 56, 
                    total_proposed_residential_units = 56, 
                    proposed_1_bed_units = 56, 
                    proposed_2_bed_units = 56, 
                    proposed_3_bed_units = 56, 
                    proposed_4_plus_bed_units = 56, 
                    affordable_housing_units = 56, 
                    proposed_terraced_count = 56, 
                    proposed_semi_count = 56, 
                    proposed_detached_count = 56, 
                    proposed_flat_count = 56, 
                    proposed_market_units = 56, 
                    proposed_affordable_units = 56, 
                    proposed_shared_ownership_units = 56, 
                    proposed_social_rent_units = 56, 
                    units_to_be_added = [
                        ibex_client.models.unit_breakdown_item_schema.UnitBreakdownItemSchema(
                            residential_unit_type = '', 
                            tenure = '', 
                            development_type = '', 
                            number_of_units = 56, 
                            bedrooms_per_unit = 56, 
                            provider = '', 
                            gia_per_unit = 1.337, )
                        ], 
                    units_to_be_lost = [
                        ibex_client.models.unit_breakdown_item_schema.UnitBreakdownItemSchema(
                            residential_unit_type = '', 
                            tenure = '', 
                            development_type = '', 
                            number_of_units = 56, 
                            bedrooms_per_unit = 56, 
                            provider = '', 
                            gia_per_unit = 1.337, )
                        ], ),
                proposed_floor_area = ibex_client.models.proposed_floor_area_schema.ProposedFloorAreaSchema(
                    gross_internal_area_to_add_sqm = 1.337, 
                    existing_gross_floor_area_sqm = 1.337, 
                    proposed_gross_floor_area_sqm = 1.337, 
                    floor_area_to_be_lost_sqm = 1.337, 
                    floor_area_to_be_gained_sqm = 1.337, ),
                num_comments_received = 56
            )
        else:
            return SearchResponseSchema(
                council_id = 56,
                council_name = '',
                planning_reference = '',
                url = '',
                proposal = '',
                raw_address = '',
                raw_application_type = '',
                normalised_application_type = 'non-material amendment',
                application_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                decided_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                raw_decision = '',
                normalised_decision = 'Approved',
                geometry = '',
        )
        """

    def testSearchResponseSchema(self):
        """Test SearchResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
