# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.normalised_decision_enum import NormalisedDecisionEnum

class TestNormalisedDecisionEnum(unittest.TestCase):
    """NormalisedDecisionEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNormalisedDecisionEnum(self):
        """Test NormalisedDecisionEnum"""
        # inst = NormalisedDecisionEnum()

if __name__ == '__main__':
    unittest.main()
