# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.search_filters_schema import SearchFiltersSchema

class TestSearchFiltersSchema(unittest.TestCase):
    """SearchFiltersSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchFiltersSchema:
        """Test SearchFiltersSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchFiltersSchema`
        """
        model = SearchFiltersSchema()
        if include_optional:
            return SearchFiltersSchema(
                normalised_application_type = [
                    'non-material amendment'
                    ],
                project_type = [
                    'small residential'
                    ],
                normalised_decision = [
                    'Approved'
                    ],
                num_new_houses = ibex_client.models.num_new_houses_filter_schema.NumNewHousesFilterSchema(
                    min = 56, 
                    max = 56, )
            )
        else:
            return SearchFiltersSchema(
        )
        """

    def testSearchFiltersSchema(self):
        """Test SearchFiltersSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
