# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.normalised_application_type_enum import NormalisedApplicationTypeEnum

class TestNormalisedApplicationTypeEnum(unittest.TestCase):
    """NormalisedApplicationTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNormalisedApplicationTypeEnum(self):
        """Test NormalisedApplicationTypeEnum"""
        # inst = NormalisedApplicationTypeEnum()

if __name__ == '__main__':
    unittest.main()
