# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.unit_breakdown_item_schema import UnitBreakdownItemSchema

class TestUnitBreakdownItemSchema(unittest.TestCase):
    """UnitBreakdownItemSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnitBreakdownItemSchema:
        """Test UnitBreakdownItemSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnitBreakdownItemSchema`
        """
        model = UnitBreakdownItemSchema()
        if include_optional:
            return UnitBreakdownItemSchema(
                residential_unit_type = '',
                tenure = '',
                development_type = '',
                number_of_units = 56,
                bedrooms_per_unit = 56,
                provider = '',
                gia_per_unit = 1.337
            )
        else:
            return UnitBreakdownItemSchema(
        )
        """

    def testUnitBreakdownItemSchema(self):
        """Test UnitBreakdownItemSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
