# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.project_type_enum import ProjectTypeEnum

class TestProjectTypeEnum(unittest.TestCase):
    """ProjectTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectTypeEnum(self):
        """Test ProjectTypeEnum"""
        # inst = ProjectTypeEnum()

if __name__ == '__main__':
    unittest.main()
