# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.number_of_applications_schema import NumberOfApplicationsSchema

class TestNumberOfApplicationsSchema(unittest.TestCase):
    """NumberOfApplicationsSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NumberOfApplicationsSchema:
        """Test NumberOfApplicationsSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NumberOfApplicationsSchema`
        """
        model = NumberOfApplicationsSchema()
        if include_optional:
            return NumberOfApplicationsSchema(
                non_material_amendment = 56,
                discharge_of_conditions = 56,
                listed_building_consent = 56,
                advertisement_consent = 56,
                householder_planning_application = 56,
                tree_preservation_order = 56,
                lawful_development = 56,
                change_of_use = 56,
                full_planning_application = 56,
                conservation_area = 56,
                utilities = 56,
                unknown = 56,
                environmental_impact = 56,
                section_106 = 56,
                pre_application = 56,
                other = 56
            )
        else:
            return NumberOfApplicationsSchema(
        )
        """

    def testNumberOfApplicationsSchema(self):
        """Test NumberOfApplicationsSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
