# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.applications_request_schema import ApplicationsRequestSchema

class TestApplicationsRequestSchema(unittest.TestCase):
    """ApplicationsRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationsRequestSchema:
        """Test ApplicationsRequestSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationsRequestSchema`
        """
        model = ApplicationsRequestSchema()
        if include_optional:
            return ApplicationsRequestSchema(
                input = ibex_client.models.application_search_parameters.Application Search Parameters(
                    date_range_type = 'validated', 
                    date_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    date_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    council_id = [
                        1.337
                        ], 
                    page = 1.337, 
                    page_size = 1.337, ),
                extensions = ibex_client.models.application_data_extensions.Application Data Extensions(
                    project_type = True, 
                    heading = True, 
                    appeals = True, 
                    num_new_houses = True, 
                    document_metadata = True, 
                    proposed_unit_mix = True, 
                    proposed_floor_area = True, 
                    num_comments_received = True, ),
                filters = ibex_client.models.application_search_filters.Application Search Filters(
                    normalised_application_type = [
                        'non-material amendment'
                        ], 
                    keywords = [
                        ''
                        ], 
                    normalised_decision = [
                        'Approved'
                        ], 
                    num_new_houses = ibex_client.models.num_new_houses_filter_schema.NumNewHousesFilterSchema(
                        min = 56, 
                        max = 56, ), )
            )
        else:
            return ApplicationsRequestSchema(
                input = ibex_client.models.application_search_parameters.Application Search Parameters(
                    date_range_type = 'validated', 
                    date_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    date_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    council_id = [
                        1.337
                        ], 
                    page = 1.337, 
                    page_size = 1.337, ),
        )
        """

    def testApplicationsRequestSchema(self):
        """Test ApplicationsRequestSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
