# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.applications_extensions_schema import ApplicationsExtensionsSchema

class TestApplicationsExtensionsSchema(unittest.TestCase):
    """ApplicationsExtensionsSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationsExtensionsSchema:
        """Test ApplicationsExtensionsSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationsExtensionsSchema`
        """
        model = ApplicationsExtensionsSchema()
        if include_optional:
            return ApplicationsExtensionsSchema(
                project_type = True,
                heading = True,
                appeals = True,
                num_new_houses = True,
                document_metadata = True,
                proposed_unit_mix = True,
                proposed_floor_area = True,
                num_comments_received = True
            )
        else:
            return ApplicationsExtensionsSchema(
        )
        """

    def testApplicationsExtensionsSchema(self):
        """Test ApplicationsExtensionsSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
