# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.proposed_floor_area_schema import ProposedFloorAreaSchema

class TestProposedFloorAreaSchema(unittest.TestCase):
    """ProposedFloorAreaSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProposedFloorAreaSchema:
        """Test ProposedFloorAreaSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProposedFloorAreaSchema`
        """
        model = ProposedFloorAreaSchema()
        if include_optional:
            return ProposedFloorAreaSchema(
                gross_internal_area_to_add_sqm = 1.337,
                existing_gross_floor_area_sqm = 1.337,
                proposed_gross_floor_area_sqm = 1.337,
                floor_area_to_be_lost_sqm = 1.337,
                floor_area_to_be_gained_sqm = 1.337
            )
        else:
            return ProposedFloorAreaSchema(
        )
        """

    def testProposedFloorAreaSchema(self):
        """Test ProposedFloorAreaSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
