# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.search_request_schema import SearchRequestSchema

class TestSearchRequestSchema(unittest.TestCase):
    """SearchRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchRequestSchema:
        """Test SearchRequestSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchRequestSchema`
        """
        model = SearchRequestSchema()
        if include_optional:
            return SearchRequestSchema(
                input = None,
                extensions = ibex_client.models.search_extensions.Search Extensions(
                    appeals = True, 
                    centre_point = True, 
                    heading = True, 
                    unlimited_radius = True, 
                    project_type = True, 
                    num_new_houses = True, 
                    document_metadata = True, 
                    proposed_unit_mix = True, 
                    proposed_floor_area = True, 
                    num_comments_received = True, ),
                filters = ibex_client.models.search_filters.Search Filters(
                    normalised_application_type = [
                        'non-material amendment'
                        ], 
                    project_type = [
                        'small residential'
                        ], 
                    normalised_decision = [
                        'Approved'
                        ], 
                    num_new_houses = ibex_client.models.num_new_houses_filter_schema.NumNewHousesFilterSchema(
                        min = 56, 
                        max = 56, ), )
            )
        else:
            return SearchRequestSchema(
                input = None,
        )
        """

    def testSearchRequestSchema(self):
        """Test SearchRequestSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
