# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.document_metadata_item_schema import DocumentMetadataItemSchema

class TestDocumentMetadataItemSchema(unittest.TestCase):
    """DocumentMetadataItemSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentMetadataItemSchema:
        """Test DocumentMetadataItemSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentMetadataItemSchema`
        """
        model = DocumentMetadataItemSchema()
        if include_optional:
            return DocumentMetadataItemSchema(
                date_published = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                document_type = '',
                description = '',
                document_link = ''
            )
        else:
            return DocumentMetadataItemSchema(
        )
        """

    def testDocumentMetadataItemSchema(self):
        """Test DocumentMetadataItemSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
