# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.average_decision_time_schema import AverageDecisionTimeSchema

class TestAverageDecisionTimeSchema(unittest.TestCase):
    """AverageDecisionTimeSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AverageDecisionTimeSchema:
        """Test AverageDecisionTimeSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AverageDecisionTimeSchema`
        """
        model = AverageDecisionTimeSchema()
        if include_optional:
            return AverageDecisionTimeSchema(
                small_residential = 1.337,
                tree = 1.337,
                large_residential = 1.337,
                home_improvement = 1.337,
                mixed = 1.337,
                medium_residential = 1.337
            )
        else:
            return AverageDecisionTimeSchema(
        )
        """

    def testAverageDecisionTimeSchema(self):
        """Test AverageDecisionTimeSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
