# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.stats_request_schema import StatsRequestSchema

class TestStatsRequestSchema(unittest.TestCase):
    """StatsRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsRequestSchema:
        """Test StatsRequestSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsRequestSchema`
        """
        model = StatsRequestSchema()
        if include_optional:
            return StatsRequestSchema(
                input = ibex_client.models.stats_request_schema_input.StatsRequestSchema_input(
                    council_id = 56, 
                    date_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    date_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
            )
        else:
            return StatsRequestSchema(
                input = ibex_client.models.stats_request_schema_input.StatsRequestSchema_input(
                    council_id = 56, 
                    date_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    date_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
        )
        """

    def testStatsRequestSchema(self):
        """Test StatsRequestSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
