# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.council_development_activity_level_enum import CouncilDevelopmentActivityLevelEnum

class TestCouncilDevelopmentActivityLevelEnum(unittest.TestCase):
    """CouncilDevelopmentActivityLevelEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCouncilDevelopmentActivityLevelEnum(self):
        """Test CouncilDevelopmentActivityLevelEnum"""
        # inst = CouncilDevelopmentActivityLevelEnum()

if __name__ == '__main__':
    unittest.main()
