# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.search_input_schema import SearchInputSchema

class TestSearchInputSchema(unittest.TestCase):
    """SearchInputSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchInputSchema:
        """Test SearchInputSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchInputSchema`
        """
        model = SearchInputSchema()
        if include_optional:
            return SearchInputSchema(
                date_range_type = 'validated',
                date_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                srid = 1.337,
                radius = 1.337,
                coordinates = [
                    1.337
                    ],
                polygon = ibex_client.models.search_area_polygon.Search Area Polygon(
                    geometry = ibex_client.models.polygon_request_schema_geometry.PolygonRequestSchema_geometry(
                        type = 'Polygon', 
                        coordinates = [
                            [
                                [
                                    1.337
                                    ]
                                ]
                            ], ), ),
                page = 1.337,
                page_size = 1.337
            )
        else:
            return SearchInputSchema(
                srid = 1.337,
                radius = 1.337,
                coordinates = [
                    1.337
                    ],
                polygon = ibex_client.models.search_area_polygon.Search Area Polygon(
                    geometry = ibex_client.models.polygon_request_schema_geometry.PolygonRequestSchema_geometry(
                        type = 'Polygon', 
                        coordinates = [
                            [
                                [
                                    1.337
                                    ]
                                ]
                            ], ), ),
        )
        """

    def testSearchInputSchema(self):
        """Test SearchInputSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
