# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.proposed_unit_mix_schema import ProposedUnitMixSchema

class TestProposedUnitMixSchema(unittest.TestCase):
    """ProposedUnitMixSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProposedUnitMixSchema:
        """Test ProposedUnitMixSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProposedUnitMixSchema`
        """
        model = ProposedUnitMixSchema()
        if include_optional:
            return ProposedUnitMixSchema(
                total_existing_residential_units = 56,
                total_proposed_residential_units = 56,
                proposed_1_bed_units = 56,
                proposed_2_bed_units = 56,
                proposed_3_bed_units = 56,
                proposed_4_plus_bed_units = 56,
                affordable_housing_units = 56,
                proposed_terraced_count = 56,
                proposed_semi_count = 56,
                proposed_detached_count = 56,
                proposed_flat_count = 56,
                proposed_market_units = 56,
                proposed_affordable_units = 56,
                proposed_shared_ownership_units = 56,
                proposed_social_rent_units = 56,
                units_to_be_added = [
                    ibex_client.models.unit_breakdown_item_schema.UnitBreakdownItemSchema(
                        residential_unit_type = '', 
                        tenure = '', 
                        development_type = '', 
                        number_of_units = 56, 
                        bedrooms_per_unit = 56, 
                        provider = '', 
                        gia_per_unit = 1.337, )
                    ],
                units_to_be_lost = [
                    ibex_client.models.unit_breakdown_item_schema.UnitBreakdownItemSchema(
                        residential_unit_type = '', 
                        tenure = '', 
                        development_type = '', 
                        number_of_units = 56, 
                        bedrooms_per_unit = 56, 
                        provider = '', 
                        gia_per_unit = 1.337, )
                    ]
            )
        else:
            return ProposedUnitMixSchema(
        )
        """

    def testProposedUnitMixSchema(self):
        """Test ProposedUnitMixSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
