# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.base_applications_schema import BaseApplicationsSchema

class TestBaseApplicationsSchema(unittest.TestCase):
    """BaseApplicationsSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseApplicationsSchema:
        """Test BaseApplicationsSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseApplicationsSchema`
        """
        model = BaseApplicationsSchema()
        if include_optional:
            return BaseApplicationsSchema(
                council_id = 56,
                council_name = '',
                planning_reference = '',
                url = '',
                proposal = '',
                raw_address = '',
                raw_application_type = '',
                normalised_application_type = 'non-material amendment',
                application_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                decided_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                raw_decision = '',
                normalised_decision = 'Approved',
                geometry = ''
            )
        else:
            return BaseApplicationsSchema(
                council_id = 56,
                council_name = '',
                planning_reference = '',
                url = '',
                proposal = '',
                raw_address = '',
                raw_application_type = '',
                normalised_application_type = 'non-material amendment',
                application_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                decided_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                raw_decision = '',
                normalised_decision = 'Approved',
                geometry = '',
        )
        """

    def testBaseApplicationsSchema(self):
        """Test BaseApplicationsSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
