# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.api.planning_statistics_api import PlanningStatisticsApi


class TestPlanningStatisticsApi(unittest.TestCase):
    """PlanningStatisticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlanningStatisticsApi()

    def tearDown(self) -> None:
        pass

    def test_stats_post(self) -> None:
        """Test case for stats_post

        Get council planning statistics
        """
        pass


if __name__ == '__main__':
    unittest.main()
