# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.models.radius_search_schema import RadiusSearchSchema

class TestRadiusSearchSchema(unittest.TestCase):
    """RadiusSearchSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RadiusSearchSchema:
        """Test RadiusSearchSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RadiusSearchSchema`
        """
        model = RadiusSearchSchema()
        if include_optional:
            return RadiusSearchSchema(
                radius = 1.337,
                coordinates = [
                    1.337
                    ]
            )
        else:
            return RadiusSearchSchema(
                radius = 1.337,
                coordinates = [
                    1.337
                    ],
        )
        """

    def testRadiusSearchSchema(self):
        """Test RadiusSearchSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
