# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibex_client.api.planning_applications_api import PlanningApplicationsApi


class TestPlanningApplicationsApi(unittest.TestCase):
    """PlanningApplicationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlanningApplicationsApi()

    def tearDown(self) -> None:
        pass

    def test_applications_post(self) -> None:
        """Test case for applications_post

        Search planning applications by date range and council
        """
        pass

    def test_search_post(self) -> None:
        """Test case for search_post

        Search for planning applications by location
        """
        pass


if __name__ == '__main__':
    unittest.main()
