# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AppealsSchema(BaseModel):
    """
    Details about planning appeals associated with applications, including outcomes and timelines
    """ # noqa: E501
    appeal_ref: Optional[StrictStr] = None
    appeal_url: Optional[StrictStr] = None
    start_date: Optional[date] = None
    decision_date: Optional[date] = None
    decision: Optional[StrictStr] = None
    case_type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["appeal_ref", "appeal_url", "start_date", "decision_date", "decision", "case_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppealsSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['start_date'] = None

        # set to None if decision_date (nullable) is None
        # and model_fields_set contains the field
        if self.decision_date is None and "decision_date" in self.model_fields_set:
            _dict['decision_date'] = None

        # set to None if decision (nullable) is None
        # and model_fields_set contains the field
        if self.decision is None and "decision" in self.model_fields_set:
            _dict['decision'] = None

        # set to None if case_type (nullable) is None
        # and model_fields_set contains the field
        if self.case_type is None and "case_type" in self.model_fields_set:
            _dict['case_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppealsSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "appeal_ref": obj.get("appeal_ref"),
            "appeal_url": obj.get("appeal_url"),
            "start_date": obj.get("start_date"),
            "decision_date": obj.get("decision_date"),
            "decision": obj.get("decision"),
            "case_type": obj.get("case_type")
        })
        return _obj


