# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ApplicationsExtensionsSchema(BaseModel):
    """
    Optional data extensions to include additional information like appeals and project details
    """ # noqa: E501
    project_type: Optional[StrictBool] = None
    heading: Optional[StrictBool] = None
    appeals: Optional[StrictBool] = None
    num_new_houses: Optional[StrictBool] = Field(default=None, description="Include number of new houses from extraction classifier")
    document_metadata: Optional[StrictBool] = Field(default=None, description="Include document metadata (date published, document type, description, link)")
    proposed_unit_mix: Optional[StrictBool] = Field(default=None, description="Include residential unit breakdown from extracted application forms")
    proposed_floor_area: Optional[StrictBool] = Field(default=None, description="Include floor area data from extracted application forms")
    num_comments_received: Optional[StrictBool] = Field(default=None, description="Include number of public comments received")
    __properties: ClassVar[List[str]] = ["project_type", "heading", "appeals", "num_new_houses", "document_metadata", "proposed_unit_mix", "proposed_floor_area", "num_comments_received"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplicationsExtensionsSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplicationsExtensionsSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_type": obj.get("project_type"),
            "heading": obj.get("heading"),
            "appeals": obj.get("appeals"),
            "num_new_houses": obj.get("num_new_houses"),
            "document_metadata": obj.get("document_metadata"),
            "proposed_unit_mix": obj.get("proposed_unit_mix"),
            "proposed_floor_area": obj.get("proposed_floor_area"),
            "num_comments_received": obj.get("num_comments_received")
        })
        return _obj


