# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ApplicationsInputSchema(BaseModel):
    """
    Input parameters for searching planning applications by date range and council
    """ # noqa: E501
    date_range_type: Optional[StrictStr] = Field(default=None, description="Type of date used for filtering. If empty, assumes any")
    date_to: date = Field(description="End date of applications")
    date_from: date = Field(description="Start date of applications")
    council_id: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="List of council ids to search within")
    page: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Page number - default is 1")
    page_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of applications per page - maximum and default is 1000")
    __properties: ClassVar[List[str]] = ["date_range_type", "date_to", "date_from", "council_id", "page", "page_size"]

    @field_validator('date_range_type')
    def date_range_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['validated', 'decided', 'any']):
            raise ValueError("must be one of enum values ('validated', 'decided', 'any')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplicationsInputSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplicationsInputSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date_range_type": obj.get("date_range_type"),
            "date_to": obj.get("date_to"),
            "date_from": obj.get("date_from"),
            "council_id": obj.get("council_id"),
            "page": obj.get("page"),
            "page_size": obj.get("page_size")
        })
        return _obj


