# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AverageDecisionTimeSchema(BaseModel):
    """
    Average decision time in days for each project type. Null values indicate insufficient data.
    """ # noqa: E501
    small_residential: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average days to decision for small residential projects", alias="small residential")
    tree: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average days to decision for tree-related applications")
    large_residential: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average days to decision for large residential projects", alias="large residential")
    home_improvement: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average days to decision for home improvement projects", alias="home improvement")
    mixed: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average days to decision for mixed-use projects")
    medium_residential: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average days to decision for medium residential projects", alias="medium residential")
    __properties: ClassVar[List[str]] = ["small residential", "tree", "large residential", "home improvement", "mixed", "medium residential"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AverageDecisionTimeSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if small_residential (nullable) is None
        # and model_fields_set contains the field
        if self.small_residential is None and "small_residential" in self.model_fields_set:
            _dict['small residential'] = None

        # set to None if tree (nullable) is None
        # and model_fields_set contains the field
        if self.tree is None and "tree" in self.model_fields_set:
            _dict['tree'] = None

        # set to None if large_residential (nullable) is None
        # and model_fields_set contains the field
        if self.large_residential is None and "large_residential" in self.model_fields_set:
            _dict['large residential'] = None

        # set to None if home_improvement (nullable) is None
        # and model_fields_set contains the field
        if self.home_improvement is None and "home_improvement" in self.model_fields_set:
            _dict['home improvement'] = None

        # set to None if mixed (nullable) is None
        # and model_fields_set contains the field
        if self.mixed is None and "mixed" in self.model_fields_set:
            _dict['mixed'] = None

        # set to None if medium_residential (nullable) is None
        # and model_fields_set contains the field
        if self.medium_residential is None and "medium_residential" in self.model_fields_set:
            _dict['medium residential'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AverageDecisionTimeSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "small residential": obj.get("small residential"),
            "tree": obj.get("tree"),
            "large residential": obj.get("large residential"),
            "home improvement": obj.get("home improvement"),
            "mixed": obj.get("mixed"),
            "medium residential": obj.get("medium residential")
        })
        return _obj


