# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ibex_client.models.normalised_application_type_enum import NormalisedApplicationTypeEnum
from ibex_client.models.normalised_decision_enum import NormalisedDecisionEnum
from typing import Optional, Set
from typing_extensions import Self

class BaseApplicationsSchema(BaseModel):
    """
    Base planning application information shared across all application response types
    """ # noqa: E501
    council_id: StrictInt
    council_name: StrictStr
    planning_reference: StrictStr
    url: StrictStr
    proposal: Optional[StrictStr]
    raw_address: Optional[StrictStr]
    raw_application_type: Optional[StrictStr]
    normalised_application_type: Optional[NormalisedApplicationTypeEnum]
    application_date: Optional[date]
    decided_date: Optional[date]
    raw_decision: Optional[StrictStr]
    normalised_decision: NormalisedDecisionEnum
    geometry: StrictStr
    __properties: ClassVar[List[str]] = ["council_id", "council_name", "planning_reference", "url", "proposal", "raw_address", "raw_application_type", "normalised_application_type", "application_date", "decided_date", "raw_decision", "normalised_decision", "geometry"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BaseApplicationsSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if proposal (nullable) is None
        # and model_fields_set contains the field
        if self.proposal is None and "proposal" in self.model_fields_set:
            _dict['proposal'] = None

        # set to None if raw_address (nullable) is None
        # and model_fields_set contains the field
        if self.raw_address is None and "raw_address" in self.model_fields_set:
            _dict['raw_address'] = None

        # set to None if raw_application_type (nullable) is None
        # and model_fields_set contains the field
        if self.raw_application_type is None and "raw_application_type" in self.model_fields_set:
            _dict['raw_application_type'] = None

        # set to None if normalised_application_type (nullable) is None
        # and model_fields_set contains the field
        if self.normalised_application_type is None and "normalised_application_type" in self.model_fields_set:
            _dict['normalised_application_type'] = None

        # set to None if application_date (nullable) is None
        # and model_fields_set contains the field
        if self.application_date is None and "application_date" in self.model_fields_set:
            _dict['application_date'] = None

        # set to None if decided_date (nullable) is None
        # and model_fields_set contains the field
        if self.decided_date is None and "decided_date" in self.model_fields_set:
            _dict['decided_date'] = None

        # set to None if raw_decision (nullable) is None
        # and model_fields_set contains the field
        if self.raw_decision is None and "raw_decision" in self.model_fields_set:
            _dict['raw_decision'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BaseApplicationsSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "council_id": obj.get("council_id"),
            "council_name": obj.get("council_name"),
            "planning_reference": obj.get("planning_reference"),
            "url": obj.get("url"),
            "proposal": obj.get("proposal"),
            "raw_address": obj.get("raw_address"),
            "raw_application_type": obj.get("raw_application_type"),
            "normalised_application_type": obj.get("normalised_application_type"),
            "application_date": obj.get("application_date"),
            "decided_date": obj.get("decided_date"),
            "raw_decision": obj.get("raw_decision"),
            "normalised_decision": obj.get("normalised_decision"),
            "geometry": obj.get("geometry")
        })
        return _obj


