# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CouncilDevelopmentActivityLevelEnum(str, Enum):
    """
    Development activity level for the council
    """

    """
    allowed enum values
    """
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CouncilDevelopmentActivityLevelEnum from a JSON string"""
        return cls(json.loads(json_str))


