# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NormalisedApplicationTypeEnum(str, Enum):
    """
    NormalisedApplicationTypeEnum
    """

    """
    allowed enum values
    """
    NON_MINUS_MATERIAL_AMENDMENT = 'non-material amendment'
    DISCHARGE_OF_CONDITIONS = 'discharge of conditions'
    LISTED_BUILDING_CONSENT = 'listed building consent'
    ADVERTISEMENT_CONSENT = 'advertisement consent'
    HOUSEHOLDER_PLANNING_APPLICATION = 'householder planning application'
    TREE_PRESERVATION_ORDER = 'tree preservation order'
    LAWFUL_DEVELOPMENT = 'lawful development'
    CHANGE_OF_USE = 'change of use'
    FULL_PLANNING_APPLICATION = 'full planning application'
    CONSERVATION_AREA = 'conservation area'
    UTILITIES = 'utilities'
    UNKNOWN = 'unknown'
    ENVIRONMENTAL_IMPACT = 'environmental impact'
    SECTION_106 = 'section 106'
    PRE_MINUS_APPLICATION = 'pre-application'
    OTHER = 'other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NormalisedApplicationTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


