# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class NumberOfApplicationsSchema(BaseModel):
    """
    Count of applications for each normalised application type within the specified period
    """ # noqa: E501
    non_material_amendment: Optional[StrictInt] = Field(default=None, description="Number of non-material amendment applications", alias="non-material amendment")
    discharge_of_conditions: Optional[StrictInt] = Field(default=None, description="Number of discharge of conditions applications", alias="discharge of conditions")
    listed_building_consent: Optional[StrictInt] = Field(default=None, description="Number of listed building consent applications", alias="listed building consent")
    advertisement_consent: Optional[StrictInt] = Field(default=None, description="Number of advertisement consent applications", alias="advertisement consent")
    householder_planning_application: Optional[StrictInt] = Field(default=None, description="Number of householder planning applications", alias="householder planning application")
    tree_preservation_order: Optional[StrictInt] = Field(default=None, description="Number of tree preservation order applications", alias="tree preservation order")
    lawful_development: Optional[StrictInt] = Field(default=None, description="Number of lawful development applications", alias="lawful development")
    change_of_use: Optional[StrictInt] = Field(default=None, description="Number of change of use applications", alias="change of use")
    full_planning_application: Optional[StrictInt] = Field(default=None, description="Number of full planning applications", alias="full planning application")
    conservation_area: Optional[StrictInt] = Field(default=None, description="Number of conservation area applications", alias="conservation area")
    utilities: Optional[StrictInt] = Field(default=None, description="Number of utilities applications")
    unknown: Optional[StrictInt] = Field(default=None, description="Number of applications with unknown type")
    environmental_impact: Optional[StrictInt] = Field(default=None, description="Number of environmental impact applications", alias="environmental impact")
    section_106: Optional[StrictInt] = Field(default=None, description="Number of section 106 applications", alias="section 106")
    pre_application: Optional[StrictInt] = Field(default=None, description="Number of pre-application enquiries", alias="pre-application")
    other: Optional[StrictInt] = Field(default=None, description="Number of other application types")
    __properties: ClassVar[List[str]] = ["non-material amendment", "discharge of conditions", "listed building consent", "advertisement consent", "householder planning application", "tree preservation order", "lawful development", "change of use", "full planning application", "conservation area", "utilities", "unknown", "environmental impact", "section 106", "pre-application", "other"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NumberOfApplicationsSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NumberOfApplicationsSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "non-material amendment": obj.get("non-material amendment"),
            "discharge of conditions": obj.get("discharge of conditions"),
            "listed building consent": obj.get("listed building consent"),
            "advertisement consent": obj.get("advertisement consent"),
            "householder planning application": obj.get("householder planning application"),
            "tree preservation order": obj.get("tree preservation order"),
            "lawful development": obj.get("lawful development"),
            "change of use": obj.get("change of use"),
            "full planning application": obj.get("full planning application"),
            "conservation area": obj.get("conservation area"),
            "utilities": obj.get("utilities"),
            "unknown": obj.get("unknown"),
            "environmental impact": obj.get("environmental impact"),
            "section 106": obj.get("section 106"),
            "pre-application": obj.get("pre-application"),
            "other": obj.get("other")
        })
        return _obj


