# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ProposedFloorAreaSchema(BaseModel):
    """
    Floor area data from extracted application forms
    """ # noqa: E501
    gross_internal_area_to_add_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    existing_gross_floor_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    proposed_gross_floor_area_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    floor_area_to_be_lost_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    floor_area_to_be_gained_sqm: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["gross_internal_area_to_add_sqm", "existing_gross_floor_area_sqm", "proposed_gross_floor_area_sqm", "floor_area_to_be_lost_sqm", "floor_area_to_be_gained_sqm"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProposedFloorAreaSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if gross_internal_area_to_add_sqm (nullable) is None
        # and model_fields_set contains the field
        if self.gross_internal_area_to_add_sqm is None and "gross_internal_area_to_add_sqm" in self.model_fields_set:
            _dict['gross_internal_area_to_add_sqm'] = None

        # set to None if existing_gross_floor_area_sqm (nullable) is None
        # and model_fields_set contains the field
        if self.existing_gross_floor_area_sqm is None and "existing_gross_floor_area_sqm" in self.model_fields_set:
            _dict['existing_gross_floor_area_sqm'] = None

        # set to None if proposed_gross_floor_area_sqm (nullable) is None
        # and model_fields_set contains the field
        if self.proposed_gross_floor_area_sqm is None and "proposed_gross_floor_area_sqm" in self.model_fields_set:
            _dict['proposed_gross_floor_area_sqm'] = None

        # set to None if floor_area_to_be_lost_sqm (nullable) is None
        # and model_fields_set contains the field
        if self.floor_area_to_be_lost_sqm is None and "floor_area_to_be_lost_sqm" in self.model_fields_set:
            _dict['floor_area_to_be_lost_sqm'] = None

        # set to None if floor_area_to_be_gained_sqm (nullable) is None
        # and model_fields_set contains the field
        if self.floor_area_to_be_gained_sqm is None and "floor_area_to_be_gained_sqm" in self.model_fields_set:
            _dict['floor_area_to_be_gained_sqm'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProposedFloorAreaSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gross_internal_area_to_add_sqm": obj.get("gross_internal_area_to_add_sqm"),
            "existing_gross_floor_area_sqm": obj.get("existing_gross_floor_area_sqm"),
            "proposed_gross_floor_area_sqm": obj.get("proposed_gross_floor_area_sqm"),
            "floor_area_to_be_lost_sqm": obj.get("floor_area_to_be_lost_sqm"),
            "floor_area_to_be_gained_sqm": obj.get("floor_area_to_be_gained_sqm")
        })
        return _obj


