# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from ibex_client.models.num_new_houses_filter_schema import NumNewHousesFilterSchema
from typing import Optional, Set
from typing_extensions import Self

class SearchFiltersSchema(BaseModel):
    """
    SearchFiltersSchema
    """ # noqa: E501
    normalised_application_type: Optional[List[StrictStr]] = Field(default=None, description="filters applications on the project type - multiple types can be a comma separated list")
    project_type: Optional[List[StrictStr]] = Field(default=None, description="filters applications on the project type - multiple types can be a comma separated list")
    normalised_decision: Optional[List[StrictStr]] = Field(default=None, description="filters applications on the normalised decision - multiple types can be a comma separated list")
    num_new_houses: Optional[NumNewHousesFilterSchema] = None
    __properties: ClassVar[List[str]] = ["normalised_application_type", "project_type", "normalised_decision", "num_new_houses"]

    @field_validator('normalised_application_type')
    def normalised_application_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['non-material amendment', 'discharge of conditions', 'listed building consent', 'advertisement consent', 'householder planning application', 'tree preservation order', 'lawful development', 'change of use', 'full planning application', 'conservation area', 'utilities', 'unknown', 'environmental impact', 'section 106', 'pre-application', 'other']):
                raise ValueError("each list item must be one of ('non-material amendment', 'discharge of conditions', 'listed building consent', 'advertisement consent', 'householder planning application', 'tree preservation order', 'lawful development', 'change of use', 'full planning application', 'conservation area', 'utilities', 'unknown', 'environmental impact', 'section 106', 'pre-application', 'other')")
        return value

    @field_validator('project_type')
    def project_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['small residential', 'tree', 'large residential', 'home improvement', 'mixed', 'medium residential']):
                raise ValueError("each list item must be one of ('small residential', 'tree', 'large residential', 'home improvement', 'mixed', 'medium residential')")
        return value

    @field_validator('normalised_decision')
    def normalised_decision_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['Approved', 'Other', 'Refused', 'Unknown', 'Validated', 'Withdrawn']):
                raise ValueError("each list item must be one of ('Approved', 'Other', 'Refused', 'Unknown', 'Validated', 'Withdrawn')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchFiltersSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of num_new_houses
        if self.num_new_houses:
            _dict['num_new_houses'] = self.num_new_houses.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchFiltersSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "normalised_application_type": obj.get("normalised_application_type"),
            "project_type": obj.get("project_type"),
            "normalised_decision": obj.get("normalised_decision"),
            "num_new_houses": NumNewHousesFilterSchema.from_dict(obj["num_new_houses"]) if obj.get("num_new_houses") is not None else None
        })
        return _obj


