# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ibex_client.models.appeals_schema import AppealsSchema
from ibex_client.models.document_metadata_item_schema import DocumentMetadataItemSchema
from ibex_client.models.normalised_application_type_enum import NormalisedApplicationTypeEnum
from ibex_client.models.normalised_decision_enum import NormalisedDecisionEnum
from ibex_client.models.project_type_enum import ProjectTypeEnum
from ibex_client.models.proposed_floor_area_schema import ProposedFloorAreaSchema
from ibex_client.models.proposed_unit_mix_schema import ProposedUnitMixSchema
from typing import Optional, Set
from typing_extensions import Self

class SearchResponseSchema(BaseModel):
    """
    SearchResponseSchema
    """ # noqa: E501
    council_id: StrictInt
    council_name: StrictStr
    planning_reference: StrictStr
    url: StrictStr
    proposal: StrictStr
    raw_address: StrictStr
    raw_application_type: StrictStr
    normalised_application_type: Optional[NormalisedApplicationTypeEnum]
    application_date: date
    decided_date: date
    raw_decision: StrictStr
    normalised_decision: NormalisedDecisionEnum
    geometry: StrictStr
    appeals: Optional[List[AppealsSchema]] = Field(default=None, description="Appeals associated with this application (only present if appeals extension requested)")
    project_type: Optional[ProjectTypeEnum] = None
    centre_point: Optional[StrictStr] = Field(default=None, description="Center point of the geometry (only present if centre_point extension requested)")
    heading: Optional[StrictStr] = None
    num_new_houses: Optional[StrictInt] = Field(default=None, description="Number of new houses from extraction classifier (only present if num_new_houses extension requested)")
    document_metadata: Optional[List[DocumentMetadataItemSchema]] = Field(default=None, description="Document metadata (only present if document_metadata extension requested)")
    proposed_unit_mix: Optional[ProposedUnitMixSchema] = Field(default=None, description="Residential unit breakdown (only present if proposed_unit_mix extension requested)")
    proposed_floor_area: Optional[ProposedFloorAreaSchema] = Field(default=None, description="Floor area data (only present if proposed_floor_area extension requested)")
    num_comments_received: Optional[StrictInt] = Field(default=None, description="Number of public comments received (only present if num_comments_received extension requested)")
    __properties: ClassVar[List[str]] = ["council_id", "council_name", "planning_reference", "url", "proposal", "raw_address", "raw_application_type", "normalised_application_type", "application_date", "decided_date", "raw_decision", "normalised_decision", "geometry", "appeals", "project_type", "centre_point", "heading", "num_new_houses", "document_metadata", "proposed_unit_mix", "proposed_floor_area", "num_comments_received"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in appeals (list)
        _items = []
        if self.appeals:
            for _item_appeals in self.appeals:
                if _item_appeals:
                    _items.append(_item_appeals.to_dict())
            _dict['appeals'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in document_metadata (list)
        _items = []
        if self.document_metadata:
            for _item_document_metadata in self.document_metadata:
                if _item_document_metadata:
                    _items.append(_item_document_metadata.to_dict())
            _dict['document_metadata'] = _items
        # override the default output from pydantic by calling `to_dict()` of proposed_unit_mix
        if self.proposed_unit_mix:
            _dict['proposed_unit_mix'] = self.proposed_unit_mix.to_dict()
        # override the default output from pydantic by calling `to_dict()` of proposed_floor_area
        if self.proposed_floor_area:
            _dict['proposed_floor_area'] = self.proposed_floor_area.to_dict()
        # set to None if normalised_application_type (nullable) is None
        # and model_fields_set contains the field
        if self.normalised_application_type is None and "normalised_application_type" in self.model_fields_set:
            _dict['normalised_application_type'] = None

        # set to None if appeals (nullable) is None
        # and model_fields_set contains the field
        if self.appeals is None and "appeals" in self.model_fields_set:
            _dict['appeals'] = None

        # set to None if project_type (nullable) is None
        # and model_fields_set contains the field
        if self.project_type is None and "project_type" in self.model_fields_set:
            _dict['project_type'] = None

        # set to None if centre_point (nullable) is None
        # and model_fields_set contains the field
        if self.centre_point is None and "centre_point" in self.model_fields_set:
            _dict['centre_point'] = None

        # set to None if heading (nullable) is None
        # and model_fields_set contains the field
        if self.heading is None and "heading" in self.model_fields_set:
            _dict['heading'] = None

        # set to None if num_new_houses (nullable) is None
        # and model_fields_set contains the field
        if self.num_new_houses is None and "num_new_houses" in self.model_fields_set:
            _dict['num_new_houses'] = None

        # set to None if document_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.document_metadata is None and "document_metadata" in self.model_fields_set:
            _dict['document_metadata'] = None

        # set to None if num_comments_received (nullable) is None
        # and model_fields_set contains the field
        if self.num_comments_received is None and "num_comments_received" in self.model_fields_set:
            _dict['num_comments_received'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "council_id": obj.get("council_id"),
            "council_name": obj.get("council_name"),
            "planning_reference": obj.get("planning_reference"),
            "url": obj.get("url"),
            "proposal": obj.get("proposal"),
            "raw_address": obj.get("raw_address"),
            "raw_application_type": obj.get("raw_application_type"),
            "normalised_application_type": obj.get("normalised_application_type"),
            "application_date": obj.get("application_date"),
            "decided_date": obj.get("decided_date"),
            "raw_decision": obj.get("raw_decision"),
            "normalised_decision": obj.get("normalised_decision"),
            "geometry": obj.get("geometry"),
            "appeals": [AppealsSchema.from_dict(_item) for _item in obj["appeals"]] if obj.get("appeals") is not None else None,
            "project_type": obj.get("project_type"),
            "centre_point": obj.get("centre_point"),
            "heading": obj.get("heading"),
            "num_new_houses": obj.get("num_new_houses"),
            "document_metadata": [DocumentMetadataItemSchema.from_dict(_item) for _item in obj["document_metadata"]] if obj.get("document_metadata") is not None else None,
            "proposed_unit_mix": ProposedUnitMixSchema.from_dict(obj["proposed_unit_mix"]) if obj.get("proposed_unit_mix") is not None else None,
            "proposed_floor_area": ProposedFloorAreaSchema.from_dict(obj["proposed_floor_area"]) if obj.get("proposed_floor_area") is not None else None,
            "num_comments_received": obj.get("num_comments_received")
        })
        return _obj


