# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from ibex_client.models.polygon_request_schema import PolygonRequestSchema
from typing import Optional, Set
from typing_extensions import Self

class SearchInputSchema(BaseModel):
    """
    SearchInputSchema
    """ # noqa: E501
    date_range_type: Optional[StrictStr] = Field(default=None, description="Type of date used for filtering. Must be defined if either date_to and date_from are provided")
    date_to: Optional[date] = Field(default=None, description="End date of applications")
    date_from: Optional[date] = Field(default=None, description="Start date of applications")
    srid: Union[StrictFloat, StrictInt] = Field(description="Valid SRID of input- currently we support 4326 (lat/long) or 27700 (easting/northing)")
    radius: Union[StrictFloat, StrictInt] = Field(description="Radius of the search area in metres")
    coordinates: Annotated[List[Union[StrictFloat, StrictInt]], Field(min_length=2, max_length=2)] = Field(description="Coordinates of the center of the search area - either [long,lat] or [easting,northing]")
    polygon: PolygonRequestSchema
    page: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Page number - default is 1")
    page_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of applications per page - maximum and default is 5000")
    __properties: ClassVar[List[str]] = ["date_range_type", "date_to", "date_from", "srid", "radius", "coordinates", "polygon", "page", "page_size"]

    @field_validator('date_range_type')
    def date_range_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['validated', 'decided', 'any']):
            raise ValueError("must be one of enum values ('validated', 'decided', 'any')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchInputSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of polygon
        if self.polygon:
            _dict['polygon'] = self.polygon.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchInputSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date_range_type": obj.get("date_range_type"),
            "date_to": obj.get("date_to"),
            "date_from": obj.get("date_from"),
            "srid": obj.get("srid"),
            "radius": obj.get("radius"),
            "coordinates": obj.get("coordinates"),
            "polygon": PolygonRequestSchema.from_dict(obj["polygon"]) if obj.get("polygon") is not None else None,
            "page": obj.get("page"),
            "page_size": obj.get("page_size")
        })
        return _obj


