# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from ibex_client.models.average_decision_time_schema import AverageDecisionTimeSchema
from ibex_client.models.council_development_activity_level_enum import CouncilDevelopmentActivityLevelEnum
from ibex_client.models.number_of_applications_schema import NumberOfApplicationsSchema
from typing import Optional, Set
from typing_extensions import Self

class StatsResponseSchema(BaseModel):
    """
    Council-level planning statistics and performance metrics
    """ # noqa: E501
    council_development_activity_level: CouncilDevelopmentActivityLevelEnum
    approval_rate: Union[StrictFloat, StrictInt] = Field(description="Percentage of applications approved within the specified period")
    refusal_rate: Union[StrictFloat, StrictInt] = Field(description="Percentage of applications refused within the specified period")
    average_decision_time: AverageDecisionTimeSchema
    number_of_applications: NumberOfApplicationsSchema
    number_of_new_homes_approved: StrictInt = Field(description="Total number of new homes approved within the specified period")
    __properties: ClassVar[List[str]] = ["council_development_activity_level", "approval_rate", "refusal_rate", "average_decision_time", "number_of_applications", "number_of_new_homes_approved"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatsResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of average_decision_time
        if self.average_decision_time:
            _dict['average_decision_time'] = self.average_decision_time.to_dict()
        # override the default output from pydantic by calling `to_dict()` of number_of_applications
        if self.number_of_applications:
            _dict['number_of_applications'] = self.number_of_applications.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatsResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "council_development_activity_level": obj.get("council_development_activity_level"),
            "approval_rate": obj.get("approval_rate"),
            "refusal_rate": obj.get("refusal_rate"),
            "average_decision_time": AverageDecisionTimeSchema.from_dict(obj["average_decision_time"]) if obj.get("average_decision_time") is not None else None,
            "number_of_applications": NumberOfApplicationsSchema.from_dict(obj["number_of_applications"]) if obj.get("number_of_applications") is not None else None,
            "number_of_new_homes_approved": obj.get("number_of_new_homes_approved")
        })
        return _obj


