# coding: utf-8

"""
    Ibex Enterprise API

    Comprehensive API for accessing UK planning application data. Provides powerful search capabilities with geographic filtering and detailed application information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class UnitBreakdownItemSchema(BaseModel):
    """
    Individual unit type/tenure/bedroom combination
    """ # noqa: E501
    residential_unit_type: Optional[StrictStr] = Field(default=None, description="Type of dwelling (e.g. House, Flat, Bungalow, Semi-Detached)")
    tenure: Optional[StrictStr] = Field(default=None, description="Tenure type (e.g. Market Housing, Social Rent, Shared Ownership)")
    development_type: Optional[StrictStr] = Field(default=None, description="Type of development (e.g. New Build, Conversion)")
    number_of_units: Optional[StrictInt] = Field(default=None, description="Number of units in this category")
    bedrooms_per_unit: Optional[StrictInt] = Field(default=None, description="Number of bedrooms per unit")
    provider: Optional[StrictStr] = Field(default=None, description="Housing provider (e.g. Private, Housing Association)")
    gia_per_unit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Gross internal area per unit in sqm")
    __properties: ClassVar[List[str]] = ["residential_unit_type", "tenure", "development_type", "number_of_units", "bedrooms_per_unit", "provider", "gia_per_unit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UnitBreakdownItemSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if residential_unit_type (nullable) is None
        # and model_fields_set contains the field
        if self.residential_unit_type is None and "residential_unit_type" in self.model_fields_set:
            _dict['residential_unit_type'] = None

        # set to None if tenure (nullable) is None
        # and model_fields_set contains the field
        if self.tenure is None and "tenure" in self.model_fields_set:
            _dict['tenure'] = None

        # set to None if development_type (nullable) is None
        # and model_fields_set contains the field
        if self.development_type is None and "development_type" in self.model_fields_set:
            _dict['development_type'] = None

        # set to None if number_of_units (nullable) is None
        # and model_fields_set contains the field
        if self.number_of_units is None and "number_of_units" in self.model_fields_set:
            _dict['number_of_units'] = None

        # set to None if bedrooms_per_unit (nullable) is None
        # and model_fields_set contains the field
        if self.bedrooms_per_unit is None and "bedrooms_per_unit" in self.model_fields_set:
            _dict['bedrooms_per_unit'] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict['provider'] = None

        # set to None if gia_per_unit (nullable) is None
        # and model_fields_set contains the field
        if self.gia_per_unit is None and "gia_per_unit" in self.model_fields_set:
            _dict['gia_per_unit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UnitBreakdownItemSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "residential_unit_type": obj.get("residential_unit_type"),
            "tenure": obj.get("tenure"),
            "development_type": obj.get("development_type"),
            "number_of_units": obj.get("number_of_units"),
            "bedrooms_per_unit": obj.get("bedrooms_per_unit"),
            "provider": obj.get("provider"),
            "gia_per_unit": obj.get("gia_per_unit")
        })
        return _obj


